using Microsoft.CodeAnalysis;

namespace AvaloniaPropertySourceGenerator;

[Generator]
//[Generator(LanguageNames.CSharp)]
//#pragma warning disable RS1036 // Specify analyzer banned API enforcement setting
public class StyledPropertySourceGenerator : ISourceGenerator
//#pragma warning restore RS1036 // Specify analyzer banned API enforcement setting
{
    void ISourceGenerator.Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForPostInitialization(initialize => { });
        context.RegisterForSyntaxNotifications(() => new StyledPropertySyntaxReceiver());
    }

    void ISourceGenerator.Execute(GeneratorExecutionContext context)
    {


        // Build up the source code
        //string source = $@"""
        //    // <auto-generated/>
        //    using System;

        //    namespace TestName
        //    {{
        //        public static partial class MyTestClass
        //        {{
        //            static partial void HelloFrom(string name) => Console.WriteLine(""Generator says: Hi from "");
        //        }}            


        //    }}

         
        //    """
        //  ;
        //var typeName = mainMethod.ContainingType.Name;

        // Add the source code to the compilation
        //context.AddSource($"MyTestClass.g.cs", source);
    }

}
